CREATE USER BENEWEB IDENTIFIED BY oracle;
ALTER USER BENEWEB DEFAULT TABLESPACE users;

ALTER USER BENEWEB QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, RESOURCE, CREATE SYNONYM, CREATE VIEW 
TO BENEWEB;

drop table BENEWEB.CONTACTINFO;

create table BENEWEB.CONTACTINFO
(
name varchar(50),
is_business NUMBER(1),
is_individual NUMBER(1),
is_employee NUMBER(1),
contact_ID varchar(50),
address1 varchar(50),
address2 varchar(50),
city varchar(50),
state varchar(50),
province varchar(50),
postal_code varchar(50),
country varchar(50),
contact_name varchar(50),
email varchar(50),
phone varchar(50),
mobile varchar(50),
fax varchar(50),
timestamp_entered timestamp,
timestamp_modified timestamp,
status varchar(50),
PRIMARY KEY(name, is_business, is_individual, is_employee)
);


GRANT SELECT ON BENEWEB.CONTACTINFO TO BENEWEB;
GRANT INSERT ON BENEWEB.CONTACTINFO TO BENEWEB;
GRANT DELETE ON BENEWEB.CONTACTINFO TO BENEWEB;

INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name1',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name2',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name3',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name4',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS','Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name5',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name6',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name7',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name8',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name9',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');
INSERT INTO BENEWEB.CONTACTINFO(NAME,IS_BUSINESS,IS_INDIVIDUAL,IS_EMPLOYEE,CONTACT_ID,ADDRESS1,ADDRESS2,CITY,STATE,PROVINCE,POSTAL_CODE,COUNTRY,CONTACT_NAME,EMAIL,PHONE,MOBILE,FAX,TIMESTAMP_ENTERED,TIMESTAMP_MODIFIED,STATUS) 
VALUES ('Name0',1,0,0,'123-456-789','123Address',null,'SomeCity','Ny',null,'12345','United States',null,null,null,null,null,TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),TO_DATE('16-3-16  5:16:00','RR-MM-DD HH:MI:SS'),'Entered');

commit;
EXIT